aboutPage: true

# - markdown: redcarpet
highlighter: rouge

domain_# - name: "https://liech.ga/m"
google_analytics: ''
disqus: true
disqus_short# - name: 'emilsayahi'

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post

title: "Emil Sayahi"
tagline: ""
description: "Follow <a href=\"https://micro.blog/emsa\">@emsa on Micro.blog</a>."
credits: "Follow <a href=\"https://micro.blog/emsa\">@emsa on Micro.blog</a>."
baseurl: "https://liech.ga/m"
url: ""
markdown: "kramdown"
username: "emsa"
permalink: "/:year/:month/:day/:title.html"
relative_permalinks: false
author: "Emil Sayahi"
name: "Emil Sayahi"
gravatar_hash: ""
avatar: "https://micro.blog/emsa/avatar.jpg"
full_name: "Emil Sayahi"
bio: "A tired 'lil scriptkiddie 😪"
twitter_username: "emilsayahi"
github_username: "emilsayahi"
instagram_username: ""
paginate: 20
paginate_path: "/page/:num/"
timezone: "America/New_York"
disqus_short: "emilsayahi"
